// app/api/reports/daily-guests/route.ts
import { NextRequest, NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { User } from "@/models/User";
import { Booking } from "@/models/Booking";
import { Room } from "@/models/Room";
import dbConnect from "@/lib/db";
import { IUser, IBooking } from "@/models/types";
import { Types } from "mongoose";

// Excel generation for Daily Guest Report

// Type definitions for lean query results
interface LeanUser extends Omit<IUser, "_id"> {
  _id: string;
}

interface LeanBooking extends Omit<IBooking, "guest" | "room"> {
  guest: string | Types.ObjectId;
  room: Types.ObjectId;
}

interface GuestWithBookings extends LeanUser {
  booking?: Partial<LeanBooking> | null;
  room?: any;
}

// English to Dari (Afghan Persian) text mapping
const englishToDari: Record<string, string> = {
  // Report titles
  "Daily Guest Report": "راپور روزانه مهمانان",
  "Report Summary": "خلاصه راپور",
  "Guest Details": "جزئیات مهمانان",
  Statistics: "احصائیه",

  // Report information
  "Report Information": "معلومات راپور",
  "Report Date:": "تاریخ راپور:",
  "Generated:": "زمان تولید:",
  "Total Guests:": "مجموع مهمانان:",
  "Active Guests:": "مهمانان فعال:",
  "Total Revenue:": "مجموع عواید:",
  "Average Spent:": "متوسط خرج:",
  Metric: "متریک",
  Value: "مقدار",

  // Guest details headers
  Name: "نام",
  Email: "ایمیل",
  Phone: "شماره تلیفون",
  Nationality: "تابعیت", // This is the main one
  "Total Stays": "تعداد اقامت",
  "Check-in Date": "تاریخ ورود",
  "Check-out Date": "تاریخ خروج",
  "ID/Passport": "آی دی کارت/پاسپورت",
  "Room Number": "شماره اطاق",

  // Statistics
  "Nationality Distribution": "توزیع بر اساس تابعیت",
  "Summary Statistics": "آمار خلاصه",
  "Total Guests": "مجموع مهمانان",
  "Active Guests": "مهمانان فعال",
  "Total Revenue": "مجموع عواید",
  "Average per Guest:": "متوسط به هر مهمان:",
  "Total Stays:": "تعداد کل اقامت‌ها:",

  // Other text
  "Generated by Hotel Management System": "تولید شده توسط سیستم مدیریت هوتل",
  Page: "صفحه",
  Unknown: "ناشناخته",
  "No Booking": "بدون رزرو",
  "Date Unknown": "تاریخ ناشناخته",
  Count: "تعداد",
  // Removed duplicate "Nationality": "تابعیت" line here

  // Sample data
  "احمد محمدی": "احمد محمدی",
  "فاطمه احمدی": "فاطمه احمدی",
  "محمد علی": "محمد علی",
  افغان: "افغان",
  ایرانی: "ایرانی",

  // Currency
  افغانی: "افغانی",

  // Months and days in Dari
  January: "جنوری",
  February: "فبروری",
  March: "مارچ",
  April: "اپریل",
  May: "می",
  June: "جون",
  July: "جولای",
  August: "آگست",
  September: "سپتمبر",
  October: "اکتبر",
  November: "نومبر",
  December: "دسمبر",

  Monday: "دوشنبه",
  Tuesday: "سه‌شنبه",
  Wednesday: "چهارشنبه",
  Thursday: "پنجشنبه",
  Friday: "جمعه",
  Saturday: "شنبه",
  Sunday: "یکشنبه",
};

// Helper function to convert English to Dari
function convertToDari(text: string): string {
  // Check if the text is a date and format it in Dari
  if (text.match(/\d{1,2}\/\d{1,2}\/\d{4}/)) {
    const date = new Date(text);
    const options: Intl.DateTimeFormatOptions = {
      year: "numeric",
      month: "long",
      day: "numeric",
      calendar: "persian",
      numberingSystem: "arab",
    };
    return new Intl.DateTimeFormat("fa-AF", options).format(date);
  }

  // Check if it's a number with currency
  if (text.includes("$") || text.includes("افغانی")) {
    const number = text.replace(/[^0-9.,]/g, "");
    if (number) {
      const formatted = new Intl.NumberFormat("fa-AF").format(
        parseFloat(number.replace(/,/g, ""))
      );
      return text.includes("$") ? `${formatted} افغانی` : `${formatted} افغانی`;
    }
  }

  // Direct mapping for known texts
  return englishToDari[text] || text;
}

// Generate Excel workbook for Daily Guest Report
async function generateGuestReportExcel(
  guestsWithBookings: any[],
  reportDate: string,
  stats: any
) {
  // Dynamic import for ExcelJS to avoid server-side rendering issues
  const ExcelJSModule = await import("exceljs");
  // ExcelJS exports Workbook as a named export
  const workbook = new (ExcelJSModule as any).Workbook();

  // Set workbook properties
  const HOTEL_NAME = "Nawaz Totakhail Hotel";
  workbook.creator = `${HOTEL_NAME} - Hotel Management System`;
  workbook.lastModifiedBy = `${HOTEL_NAME} - Hotel Management System`;
  workbook.created = new Date();
  workbook.modified = new Date();

  // Create sheets with Dari names
  const summarySheet = workbook.addWorksheet("خلاصه راپور");
  const guestsSheet = workbook.addWorksheet("جزئیات مهمانان");
  const statsSheet = workbook.addWorksheet("احصائیه");

  // Generate sheets with Dari text
  addSummarySheet(summarySheet, reportDate, stats);
  addGuestsSheet(guestsSheet, guestsWithBookings);
  addStatsSheet(statsSheet, guestsWithBookings, stats);

  return workbook;
}

// Add summary sheet with hotel name and logo
function addSummarySheet(sheet: any, reportDate: string, stats: any) {
  const HOTEL_NAME = "Nawaz Totakhail Hotel";

  // Hotel name header
  sheet.mergeCells("A1:D1");
  const hotelNameCell = sheet.getCell("A1");
  hotelNameCell.value = HOTEL_NAME;
  hotelNameCell.font = {
    size: 18,
    bold: true,
    color: { argb: "FF0052A5" },
    name: "Arial",
  };
  hotelNameCell.alignment = { horizontal: "center", vertical: "middle" };
  sheet.getRow(1).height = 25;

  // Title in Dari
  sheet.mergeCells("A2:D3");
  const titleCell = sheet.getCell("A2");
  titleCell.value = "راپور روزانه مهمانان";
  titleCell.font = {
    size: 16,
    bold: true,
    color: { argb: "FFFFFFFF" },
    name: "Arial", // Use Arial for better Dari support
  };
  titleCell.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "FF0052A5" },
  };
  titleCell.alignment = {
    horizontal: "center",
    vertical: "middle",
    wrapText: true,
  };
  sheet.getRow(2).height = 30;

  // Report information in Dari
  sheet.getCell("A5").value = "معلومات راپور";
  sheet.getCell("A5").font = {
    size: 12,
    bold: true,
    color: { argb: "FF0052A5" },
    name: "Arial",
  };

  // Format date in Dari
  const formattedDate = new Date(reportDate).toLocaleDateString("fa-AF", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const formattedTime = new Date().toLocaleTimeString("fa-AF", {
    hour: "2-digit",
    minute: "2-digit",
  });

  const reportData = [
    ["تاریخ راپور:", formattedDate],
    ["زمان تولید:", `${formattedDate} - ${formattedTime}`],
    ["مجموع مهمانان:", stats.totalGuests],
    ["مهمانان فعال:", stats.activeGuests],
    [
      "مجموع عواید:",
      `${new Intl.NumberFormat("fa-AF").format(stats.totalSpent)} افغانی`,
    ],
    [
      "متوسط خرج:",
      `${new Intl.NumberFormat("fa-AF").format(
        stats.averageSpent.toFixed(2)
      )} افغانی`,
    ],
  ];

  reportData.forEach((row, index) => {
    const rowNum = index + 7;
    sheet.getCell(`A${rowNum}`).value = row[0];
    sheet.getCell(`A${rowNum}`).font = { bold: true, name: "Arial" };
    sheet.getCell(`B${rowNum}`).value = row[1];
    sheet.getCell(`B${rowNum}`).font = { name: "Arial" };
  });

  // Set column widths
  sheet.columns = [{ width: 25 }, { width: 40 }, { width: 10 }, { width: 20 }];
}

// Add guests details sheet with hotel name and logo
function addGuestsSheet(sheet: any, guestsWithBookings: any[]) {
  const HOTEL_NAME = "Nawaz Totakhail Hotel";

  // Hotel name header
  sheet.mergeCells("A1:I1");
  const hotelNameCell = sheet.getCell("A1");
  hotelNameCell.value = HOTEL_NAME;
  hotelNameCell.font = {
    size: 16,
    bold: true,
    color: { argb: "FF0052A5" },
    name: "Arial",
  };
  hotelNameCell.alignment = { horizontal: "center", vertical: "middle" };

  // Title in Dari
  sheet.mergeCells("A2:I2");
  const titleCell = sheet.getCell("A2");
  titleCell.value = "جزئیات مهمانان";
  titleCell.font = {
    size: 14,
    bold: true,
    color: { argb: "FFFFFFFF" },
    name: "Arial",
  };
  titleCell.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "FF2C3E50" },
  };
  titleCell.alignment = { horizontal: "center", vertical: "middle" };

  // Headers in Dari
  const headers = [
    "نام",
    "ایمیل",
    "شماره تلیفون",
    "تابعیت",
    "تعداد اقامت",
    "تاریخ ورود",
    "تاریخ خروج",
    "آی دی کارت/پاسپورت",
    "شماره اطاق",
  ];

  headers.forEach((header, index) => {
    const cell = sheet.getCell(4, index + 1);
    cell.value = header;
    cell.font = {
      bold: true,
      color: { argb: "FFFFFFFF" },
      name: "Arial",
    };
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF2C3E50" },
    };
    cell.alignment = { horizontal: "center", wrapText: true };
    cell.border = {
      top: { style: "thin" },
      left: { style: "thin" },
      bottom: { style: "thin" },
      right: { style: "thin" },
    };
  });

  // Guest data
  guestsWithBookings.forEach((guest, rowIndex) => {
    const formatDate = (date: Date | null | undefined) => {
      if (!date) return "تاریخ ناشناخته";
      try {
        return new Date(date).toLocaleDateString("fa-AF", {
          year: "numeric",
          month: "long",
          day: "numeric",
        });
      } catch {
        return "تاریخ ناشناخته";
      }
    };

    const getIdNumber = (guest: any) => {
      return guest.idNumber || guest.passportNumber || "ناشناخته";
    };

    const getRoomNumber = (guest: any) => {
      return guest.room?.roomNumber || "بدون رزرو";
    };

    const rowData = [
      guest.name || "ناشناخته",
      guest.email || "ناشناخته",
      guest.phone || "ناشناخته",
      guest.nationality || "ناشناخته",
      new Intl.NumberFormat("fa-AF").format(guest.totalStays || 0),
      formatDate(guest.booking?.checkInDate),
      formatDate(guest.booking?.checkOutDate),
      getIdNumber(guest),
      getRoomNumber(guest),
    ];

    rowData.forEach((value, colIndex) => {
      const cell = sheet.getCell(rowIndex + 5, colIndex + 1);
      cell.value = value;
      cell.font = { name: "Arial" };
      cell.border = {
        top: { style: "thin" },
        left: { style: "thin" },
        bottom: { style: "thin" },
        right: { style: "thin" },
      };
    });
  });

  // Set column widths
  sheet.columns = [
    { width: 25 },
    { width: 30 },
    { width: 20 },
    { width: 18 },
    { width: 15 },
    { width: 20 },
    { width: 20 },
    { width: 25 },
    { width: 18 },
  ];
}

// Add statistics sheet with hotel name
function addStatsSheet(sheet: any, guestsWithBookings: any[], stats: any) {
  const HOTEL_NAME = "Totakhail Hotel";

  // Hotel name header
  sheet.mergeCells("A1:B1");
  const hotelNameCell = sheet.getCell("A1");
  hotelNameCell.value = HOTEL_NAME;
  hotelNameCell.font = {
    size: 16,
    bold: true,
    color: { argb: "FF0052A5" },
    name: "Arial",
  };
  hotelNameCell.alignment = { horizontal: "center", vertical: "middle" };

  // Title in Dari
  sheet.mergeCells("A2:B2");
  const titleCell = sheet.getCell("A2");
  titleCell.value = "احصائیه";
  titleCell.font = {
    size: 14,
    bold: true,
    color: { argb: "FFFFFFFF" },
    name: "Arial",
  };
  titleCell.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "FF27AE60" },
  };
  titleCell.alignment = { horizontal: "center", vertical: "middle" };

  // Nationality breakdown in Dari
  sheet.getCell("A4").value = "توزیع بر اساس تابعیت";
  sheet.getCell("A4").font = { size: 12, bold: true, name: "Arial" };

  const nationalityStats = guestsWithBookings.reduce(
    (acc: Record<string, number>, guest: any) => {
      const nationality = guest.nationality || "ناشناخته";
      acc[nationality] = (acc[nationality] || 0) + 1;
      return acc;
    },
    {}
  );

  // Headers for nationality table in Dari
  sheet.getCell("A6").value = "تابعیت";
  sheet.getCell("A6").font = { bold: true, name: "Arial" };
  sheet.getCell("B6").value = "تعداد";
  sheet.getCell("B6").font = { bold: true, name: "Arial" };

  Object.entries(nationalityStats).forEach(([nationality, count], index) => {
    sheet.getCell(`A${index + 7}`).value = nationality;
    sheet.getCell(`A${index + 7}`).font = { name: "Arial" };
    sheet.getCell(`B${index + 7}`).value = new Intl.NumberFormat(
      "fa-AF"
    ).format(count as number);
    sheet.getCell(`B${index + 7}`).font = { name: "Arial" };
  });

  // Summary statistics in Dari
  const summaryStartRow = Object.keys(nationalityStats).length + 9;
  sheet.getCell(`A${summaryStartRow}`).value = "آمار خلاصه";
  sheet.getCell(`A${summaryStartRow}`).font = {
    size: 12,
    bold: true,
    name: "Arial",
  };

  const summaryData = [
    [
      "مجموع مهمانان:",
      new Intl.NumberFormat("fa-AF").format(stats.totalGuests),
    ],
    [
      "مهمانان فعال:",
      new Intl.NumberFormat("fa-AF").format(stats.activeGuests),
    ],
    [
      "مجموع عواید:",
      `${new Intl.NumberFormat("fa-AF").format(stats.totalSpent)} افغانی`,
    ],
    [
      "متوسط به هر مهمان:",
      `${new Intl.NumberFormat("fa-AF").format(
        stats.averageSpent.toFixed(2)
      )} افغانی`,
    ],
    [
      "تعداد کل اقامت‌ها:",
      new Intl.NumberFormat("fa-AF").format(stats.totalStays),
    ],
  ];

  summaryData.forEach((row, index) => {
    const rowNum = summaryStartRow + index + 2;
    sheet.getCell(`A${rowNum}`).value = row[0];
    sheet.getCell(`A${rowNum}`).font = { bold: true, name: "Arial" };
    sheet.getCell(`B${rowNum}`).value = row[1];
    sheet.getCell(`B${rowNum}`).font = { name: "Arial" };
  });
}

// Function to add logo to Excel sheet (if image exists)
async function addLogoToSheet(sheet: any, logoPath: string = "/logo.jpg") {
  try {
    // This is a placeholder for logo functionality
    // In a real implementation, you would:
    // 1. Check if the logo file exists
    // 2. Read the image file
    // 3. Add it to the Excel sheet using ExcelJS image functionality
    // For now, we'll just add a text indicator
    sheet.mergeCells("D1:E3");
    const logoCell = sheet.getCell("D1");
    logoCell.value = "[Hotel Logo]";
    logoCell.font = {
      size: 10,
      italic: true,
      color: { argb: "FF666666" },
      name: "Arial",
    };
    logoCell.alignment = { horizontal: "center", vertical: "middle" };
    logoCell.border = {
      top: { style: "thin" },
      left: { style: "thin" },
      bottom: { style: "thin" },
      right: { style: "thin" },
    };
  } catch (error) {
    console.warn("Could not add logo to Excel sheet:", error);
  }

  // Set column widths
  sheet.columns = [{ width: 25 }, { width: 25 }];
}

export async function GET(request: NextRequest) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: "غیر مجاز" }, { status: 401 });
    }

    await dbConnect();

    // Get date parameter from query (default to today)
    const searchParams = request.nextUrl.searchParams;
    const reportDate =
      searchParams.get("date") || new Date().toISOString().split("T")[0];

    // Parse the date
    const targetDate = new Date(reportDate);
    const startOfDay = new Date(targetDate.setHours(0, 0, 0, 0));
    const endOfDay = new Date(targetDate.setHours(23, 59, 59, 999));

    // Get all guests
    const guests = (await User.find({
      role: "guest",
      createdAt: {
        $gte: new Date(targetDate.getTime() - 30 * 24 * 60 * 60 * 1000), // Include last 30 days
        $lte: endOfDay,
      },
    }).lean()) as unknown as Array<IUser & { _id: string }>;

    // Get bookings with room information for these guests
    const guestIds = guests.map((guest) => guest._id);
    const bookings = (await Booking.find({
      guest: { $in: guestIds },
    })
      .populate("room", "roomNumber")
      .lean()) as unknown as Array<
      IBooking & { guest: string | Types.ObjectId; room: any }
    >;

    // Combine guest data with booking and room data
    const guestsWithBookings: (GuestWithBookings | any)[] = guests.map(
      (guest) => {
        const booking = bookings.find((b) => {
          const bookingGuestId =
            typeof b.guest === "string"
              ? b.guest
              : (b.guest as Types.ObjectId)?.toString();
          return bookingGuestId === guest._id;
        });
        return {
          ...guest,
          booking: booking || null,
          room: booking?.room || null,
        };
      }
    );

    // Calculate statistics
    let totalGuests = guestsWithBookings.length;
    let activeGuests = guestsWithBookings.filter(
      (guest) => guest.isActive
    ).length;

    let totalSpent = guestsWithBookings.reduce((sum, guest) => {
      const spent = guest.totalSpent;
      if (spent && typeof spent === "object" && "toString" in spent) {
        return sum + Number(spent.toString());
      }
      return sum + (Number(spent) || 0);
    }, 0);

    let totalStays = guestsWithBookings.reduce(
      (sum, guest) => sum + (guest.totalStays || 0),
      0
    );
    let averageSpent = totalGuests > 0 ? totalSpent / totalGuests : 0;

    // Group guests by nationality
    let nationalityStats = guestsWithBookings.reduce(
      (acc: Record<string, number>, guest) => {
        const nationality = guest.nationality || "ناشناخته";
        acc[nationality] = (acc[nationality] || 0) + 1;
        return acc;
      },
      {}
    );

    // Prepare stats object for Excel generation
    const stats = {
      totalGuests,
      activeGuests,
      totalSpent,
      totalStays,
      averageSpent,
    };

    // If no guests found, provide sample data for demonstration
    if (totalGuests === 0) {
      const sampleGuests = [
        {
          _id: "sample-1",
          name: "احمد محمدی",
          email: "ahmed.mohammadi@example.com",
          phone: "۰۷۰۰۱۲۳۴۵۶+۹۳",
          nationality: "افغان",
          idNumber: "۱۲۳۴۵۶۷۸۹",
          passportNumber: "AB1234567",
          totalStays: 3,
          totalSpent: 15000,
          isActive: true,
          createdAt: startOfDay,
          booking: {
            checkInDate: new Date(
              targetDate.getTime() - 2 * 24 * 60 * 60 * 1000
            ),
            checkOutDate: new Date(
              targetDate.getTime() + 1 * 24 * 60 * 60 * 1000
            ),
          },
          room: {
            roomNumber: "۱۰۱",
          },
        },
        {
          _id: "sample-2",
          name: "فاطمه احمدی",
          email: "fatima.ahmadi@example.com",
          phone: "۰۷۰۱۲۳۴۵۶۷+۹۳",
          nationality: "افغان",
          idNumber: "۹۸۷۶۵۴۳۲۱",
          passportNumber: "CD9876543",
          totalStays: 1,
          totalSpent: 5000,
          isActive: true,
          createdAt: startOfDay,
          booking: {
            checkInDate: new Date(
              targetDate.getTime() - 1 * 24 * 60 * 60 * 1000
            ),
            checkOutDate: new Date(
              targetDate.getTime() + 2 * 24 * 60 * 60 * 1000
            ),
          },
          room: {
            roomNumber: "۱۰۲",
          },
        },
        {
          _id: "sample-3",
          name: "محمد علی",
          email: "mohammad.ali@example.com",
          phone: "۰۷۰۲۳۴۵۶۷۸+۹۳",
          nationality: "ایرانی",
          idNumber: "۴۵۶۷۸۹۱۲۳",
          passportNumber: "EF4567891",
          totalStays: 2,
          totalSpent: 8000,
          isActive: false,
          createdAt: startOfDay,
          booking: null,
          room: null,
        },
      ];

      // Add sample data to guestsWithBookings array
      sampleGuests.forEach((guest) => {
        guestsWithBookings.push(guest);
      });

      // Recalculate statistics with sample data
      totalGuests = guestsWithBookings.length;
      activeGuests = guestsWithBookings.filter(
        (guest) => guest.isActive
      ).length;
      totalSpent = guestsWithBookings.reduce(
        (sum, guest) => sum + (Number(guest.totalSpent) || 0),
        0
      );
      totalStays = guestsWithBookings.reduce(
        (sum, guest) => sum + (guest.totalStays || 0),
        0
      );
      averageSpent = totalGuests > 0 ? totalSpent / totalGuests : 0;

      // Update nationality stats
      nationalityStats = guestsWithBookings.reduce(
        (acc: Record<string, number>, guest: GuestWithBookings) => {
          const nationality = guest.nationality || "ناشناخته";
          acc[nationality] = (acc[nationality] || 0) + 1;
          return acc;
        },
        {}
      );
    }

    // Generate Excel workbook
    try {
      const workbook = await generateGuestReportExcel(
        guestsWithBookings,
        reportDate,
        stats
      );
      const excelBuffer = await workbook.xlsx.writeBuffer();

      // Format date for filename in Dari format (YYYY-MM-DD)
      const dateForFilename = new Date(reportDate).toISOString().split("T")[0];
      const filename = `راپور-مهمانان-روزانه-${dateForFilename}.xlsx`;

      console.log(
        `Excel report generated successfully: ${filename} (${excelBuffer.byteLength} bytes)`
      );

      return new NextResponse(excelBuffer, {
        headers: {
          "Content-Type":
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
          "Content-Disposition": `attachment; filename="${encodeURIComponent(
            filename
          )}"; filename*=UTF-8''${encodeURIComponent(filename)}`,
          "Content-Length": excelBuffer.byteLength.toString(),
          "Cache-Control": "no-cache",
        },
      });
    } catch (excelError) {
      console.error("Excel generation error:", excelError);
      throw new Error("در تولید Excel مشکل ایجاد شد");
    }
  } catch (error) {
    console.error("Error generating daily guest report:", error);
    return NextResponse.json(
      { error: "در تولید راپور روزانه مهمانان مشکل ایجاد شد" },
      { status: 500 }
    );
  }
}
